version: 2.1
jobs:
  build:
    docker:
      - image: fpco/stack-build:lts
      - image: circleci/postgres:9.6-alpine
        environment:
          POSTGRES_USER: test
          POSTGRES_DB: shortener-test
          POSTGRES_PASSWORD: test
    steps:
      - checkout
      - run:
          name: Waiting for Postgres to be ready
          command: sleep 10
      - restore_cache:
          name: Restore Cached Dependencies
          keys:
            - shortener-{{ checksum "stack.yaml" }}-{{ checksum "shortener.cabal" }}
            - shortener-{{ checksum "stack.yaml" }}
      - run:
          name: Resolve/Update Dependencies
          command: stack --no-terminal -j1 setup
      - run:
          name: Run tests
          command: stack --no-terminal -j1 test
      - save_cache:
          name: Cache Dependencies
          key: shortener-{{ checksum "stack.yaml" }}-{{ checksum "shortener.cabal" }}
          paths:
            - "/root/.stack"
            - ".stack-work"
